### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by PetrosKalendralis** [kristiank/AIDAVA-annotation#3]
I am getting an error with the latest version of the script 
"UnboundLocalError: cannot access local variable 'concept_df' where it is not associated with a value"

Is it related to the inception output?

**Comment by PetrosKalendralis** [comment]
Hi Kristian,

Yes I have all the packages installed. I have just tried again and I received a different error.
***@***.***

Regards,
Petros

**Comment by kristiank** [comment]
I double-checked, and the script works for me. To clarify – you only need to put the zip file in the 'export-zips' folder, you don't need to unzip it yourself. Maybe that's why it fails.

**Comment by kristiank** [comment]
From your previous error message, I noticed you have the statistics script inside the export-zips folder. The folder layout should be different:
```text
/statistics_calculation.py
/export-zips/your-files-go-here
```
